config/routes.rb
Rails.application.routes.draw do
  
  get '/', to: 'welcome#index'

  devise_for :users
  root 'welcome#index'
  
  get '/cats', to: 'cats#index'
  
  get '/dogs', to: 'dogs#index'

  get '/cats/new', to: 'cats#new', as: 'new_cat'

  post '/cats', to: 'cats#create'

  get '/cats/:id', to: 'cats#show', as: 'cat'

  get '/cats/:id/edit', to: 'cats#edit', as: 'edit_cat'

  patch '/cats/:id', to: 'cats#update'

  put '/cats/:id', to: 'cats#update'
  
  delete '/cats/:id', to: 'cats#destroy'
  
  resources :dogs
  
  resources :cities
  
  resources :bikes
  
  resources :messages
end

app/models/bike.rb
class Bike < ActiveRecord::Base
  
end

app/models/cat.rb
class Cat < ActiveRecord::Base

end

app/models/city.rb
class City < ActiveRecord::Base
  
end

app/models/dog.rb
class Dog < ActiveRecord::Base
  
end

app/models/message.rb
class Message < ActiveRecord::Base

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  def index
    @bikes = Bike.all
    
  end
  
  def new
    @bike = Bike.new
  end
  
  def create
    @bike = Bike.create(bike_params)
    redirect_to Bike
  end
  
  def show
    @bike = Bike.find(params[:id])
  end

  def edit
    @bike = Bike.find(params[:id])
  end

  respond_to :html, :json
  def update
    @bike = Bike.find(params[:id])
    @bike.update_attributes(bike_params)
    respond_with @bike
  end
  
  def destroy
    @bike = Bike.find(params[:id])
    @bike.destroy
    redirect_to Bike
  end
  private
  def bike_params
    params.require(:bike).permit(:brand, :model, :color)
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController

  def index
    @cats = Cat.all
  end

  def new
    @cat = Cat.new
  end

  def create
    Cat.create(allowed_parameters)
    redirect_to Cat
  end

  def show
    @cat = Cat.find(params[:id])
  end

  def edit
    @cat = Cat.find(params[:id])
  end

  def update
    @cat = Cat.find(params[:id])
    @cat.update_attributes(allowed_parameters)
    redirect_to cat_path(@cat)
  end
  
  def destroy
    @cat = Cat.find(params[:id])
    @cat.destroy
    redirect_to Cat
  end

  private

  def allowed_parameters
    params.require(:cat).permit(:cat_name, :cat_color, :kittens)
  end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    @cities = City.all
  end
  
  def new
    @city = City.new
  end
  
  def create
    City.create(city_params)
    redirect_to City
  end
  
  def show
    @city = City.find(params[:id])
  end
  
  def edit
    @city = City.find(params[:id])
  end
  
  def update
    @city = City.find(params[:id])
    @city.update_attributes(city_params)
    redirect_to City
  end
  
  def destroy
    @city = City.find(params[:id])
    @city.destroy
    redirect_to City
  end
  
  private
  
  def city_params
    params.require(:city).permit(:city_name, :state, :time_zone)
  end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  def index
    @dogs = Dog.all
  end
  
  def new
    @dog = Dog.new
  end
  
  def create
    Dog.create(dog_params)
    redirect_to Dog
  end
  
  def show
    @dog = Dog.find(params[:id])
  end
  
  def edit
    @dog = Dog.find(params[:id])
  end
  
  def update
    @dog = Dog.find(params[:id])
    @dog.update_attributes(dog_params)
    redirect_to dog_path(@dog)
  end
  
  def destroy
    @dog = Dog.find(params[:id])
    @dog.destroy
    redirect_to Dog
  end
  
  private
  
  def dog_params
    params.require(:dog).permit(:dog_name, :dog_breed, :spay_neuter)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @messages = Message.all
  end
  
  def new
    @message = Message.new
  end
  
  def create
    Message.create(message_params)
    redirect_to Message
  end
  
  private
  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bikes/edit.html.erb
<%= form_for @bike do |b| %>
  <%= b.label :brand, "Brand" %>
  <%= b.text_field :brand %>
  <%= b.label :model, "Model" %>
  <%= b.text_field :model %>
  <%= b.label :color, "Color" %>
  <%= b.text_field :color %>
  <%= b.submit "Edit this Bike" %>
<% end %>

<script><%= add_gritter("This is the sexy bikes edit page!") %></script>

app/views/bikes/index.html.erb
Welcome!

<%= link_to "Add Bike", new_bike_path %>

<% @bikes.each do |bike| %>
<%= link_to bike.model, bike_path(bike)%>
<% end %>

app/views/bikes/new.html.erb
<%= form_for @bike do |b| %>
  <%= b.label :brand, "Brand" %>
  <%= b.text_field :brand %>
  <%= b.label :model, "Model" %>
  <%= b.text_field :model %>
  <%= b.label :color, "Color" %>
  <%= b.text_field :color %>
<%= b.submit "Add this Bike" %>
<% end %>
  

app/views/bikes/show.html.erb
<%= best_in_place @bike, :brand %>

<%= @bike.brand %>
<%= @bike.model %>
<%= @bike.color %>

<%= link_to "Edit Bike", edit_bike_path %>
<%= link_to "Delete Bike", bike_path, method:"delete" %>

app/views/cats/edit.html.erb
<%= form_for @cat do |f| %>
  <%= f.label :cat_name, "Cat Name" %>
  <%= f.text_field :cat_name %>
  <%= f.label :cat_color, "Cat Color" %>
  <%= f.text_field :cat_color %>
  <%= f.label :kittens, "Kittens" %>
  <%= f.text_field :kittens %>
  <%= f.submit "Update Cat" %>
  <% end %>

app/views/cats/index.html.erb
<%= link_to "Create Cat", new_cat_path %>

<% @cats.each do |cat| %>
<%= link_to cat.cat_name, cat_path(cat) %>
<% end %>

app/views/cats/new.html.erb
<%= form_for @cat do |f| %>
  <%= f.label :cat_name, "Cat Name" %>
  <%= f.text_field :cat_name %>
  <%= f.label :cat_color, "Cat Color" %>
  <%= f.text_field :cat_color %>
  <%= f.label :kittens, "Kittens" %>
  <%= f.text_field :kittens %>
  <%= f.submit "Add Cat" %>
<% end %>

app/views/cats/show.html.erb
<%= @cat.cat_name %>
<%= @cat.cat_color %>
<%= @cat.kittens %>

<%= link_to "Update Cat", edit_cat_path %>
<%= link_to "Delete Cat", cat_path, method:'delete' %>

app/views/cities/edit.html.erb
<%= form_for @city do |f| %>
  <%= f.label :city_name, 'City Name' %>
  <%= f.text_field :city_name, autofocus: 'autofocus' %>
  <%= f.label :state, 'State' %>
  <%= f.label :time_zone, 'Please select a time zone' %>
  <%= f.select(:time_zone, options_for_select(['Eastern', 'Central', 'Mountain', 'Pacific'])) %>
  <%= f.submit 'Update City' %>
<% end %>

app/views/cities/index.html.erb
<%= link_to "Create City", new_city_path %>

<ul><% @cities.each do |city| %>
 <li><b><%= link_to city.city_name, city_path(city) %>, <%= city.state %></b>
<% end %>
</ul>

app/views/cities/new.html.erb
<%= form_for @city do |f| %>
  <%= f.label :city_name, "City Name" %>
  <%= f.text_field :city_name %>
  <%= f.label :state, "State" %>
  <%= f.text_field :state %>
  <%= f.label :time_zone, "Please select a time zone" %>
  <%= f.select(:time_zone, options_for_select(['Eastern', 'Central', 'Mountain', 'Pacific'])) %>
  <%= f.submit "Add City" %>
<% end %>

app/views/cities/show.html.erb
<b><%= @city.city_name %>, <%= @city.state %></b> is in the <%= @city.time_zone %> Time Zone
<%= link_to 'Edit City', edit_city_path %>
<%= link_to 'Delete City', city_path, method:"delete" %>

app/views/dogs/edit.html.erb
<%= form_for @dog do |f| %>
  <%= f.label :dog_name, 'Dog Name' %>
  <%= f.text_field :dog_name, autofocus: 'autofocus' %>
  <%= f.label :dog_breed, 'Dog Breed' %>
  <%= f.text_field :dog_breed %>
  <%= f.label :spay_neuter, 'Spayed/Neutered?' %>
  <%= f.check_box :spay_neuter %>
  <%= f.submit "Update Dog" %>
<% end %>

app/views/dogs/index.html.erb
<%= link_to "Create Dog", new_dog_path %>

<% @dogs.each do |dog| %>
<%= link_to dog.dog_name, dog_path(dog) %>
<% end %>

app/views/dogs/new.html.erb
<%= form_for @dog do |f| %>
  <%= f.label :dog_name, 'Dog Name' %>
  <%= f.text_field :dog_name, autofocus: 'autofocus' %>
  <%= f.label :dog_breed, 'Dog Breed' %>
  <%= f.text_field :dog_breed %>
  <%= f.label :spay_neuter, 'Spayed/Neutered?' %>
  <%= f.check_box :spay_neuter %>
  <%= f.submit "Add Dog" %>
<% end %>

app/views/dogs/show.html.erb
<ul>
  <li><%= @dog.dog_name %>
<li><%= @dog.dog_breed %>
<li><% if @dog.spay_neuter == true %>
    <%='Spayed/Neutered' %>
<% else %>
  <%= 'Not Spayed/Neutered' %>
  <% end %>
</ul><br>

<%= link_to 'Update Dog', edit_dog_path %>
<%= link_to 'Delete Dog', dog_path, method:"delete" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsCrud</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<p class="navbar-text pull-right">
  <% if user_signed_in? %>
    Logged in as <strong><%= current_user.email %></strong>.
    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>
  
<%= yield %>


</body>
</html>

app/views/messages/index.html.erb
<%= link_to 'Add a Message', new_message_path %><br><br>
Content:
<br><br>
<% @messages.each do |message| %>
<%= message.content %><br>
<% end %>

app/views/messages/new.html.erb
<%= form_for @message do |f| %>
  <%= f.label :content, 'Content' %>
  <%= f.text_field :content, autofocus: 'autofocus' %>
  <%= f.submit "Send" %>
<% end %>

app/views/welcome/index.html.erb
<%= link_to "Cats", cats_path %>
<%= link_to "Dogs", dogs_path %>
<%= link_to "Cities", cities_path %>
<%= link_to "Bikes", bikes_path %>
<%= link_to "Messages", messages_path %>